title: やまだ Blog
description: やまだのブログ。ぼちぼち更新していきます。
lang: ja
show_downloads: false
github.is_project_page: false
theme: jekyll-theme-cayman
baseurl: "/blog"
url: "https://r-40021.github.io/"
ogp: "https://r-40021.github.io/blog/assets/img/ogp.png"
paginate: 5
paginate_path: "blog/page:num"
